### POST DIRECTION
POST http://localhost:3001/direction
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInJvbGUiOiJzdXBlcl9hZG1pbiIsImlhdCI6MTY4Njc1NzAwOCwiZXhwIjoxNjg2ODQzNDA4fQ.4rDRuaMqMbg8ER4xt2w553N1_FcasjM6dj8a1VvSDRI
Content-Type: application/json

{
  "name": "dezayin"
}

### GET DIRECTION
GET http://localhost:3001/direction
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInJvbGUiOiJzdXBlcl9hZG1pbiIsImlhdCI6MTY4Njc1NzAwOCwiZXhwIjoxNjg2ODQzNDA4fQ.4rDRuaMqMbg8ER4xt2w553N1_FcasjM6dj8a1VvSDRI
Content-Type: application/json

### GET SIGLE DIRECTION
GET http://localhost:3001/direction/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInJvbGUiOiJzdXBlcl9hZG1pbiIsImlhdCI6MTY4Njc1NzAwOCwiZXhwIjoxNjg2ODQzNDA4fQ.4rDRuaMqMbg8ER4xt2w553N1_FcasjM6dj8a1VvSDRI
Content-Type: application/json


### UPDATE DIRECTION
PATCH http://localhost:3001/direction/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInJvbGUiOiJzdXBlcl9hZG1pbiIsImlhdCI6MTY4Njc1NzAwOCwiZXhwIjoxNjg2ODQzNDA4fQ.4rDRuaMqMbg8ER4xt2w553N1_FcasjM6dj8a1VvSDRI
Content-Type: application/json

{
  "name": "dasturlash"
}


### DELETE DIRECTION
DELETE http://localhost:3001/direction/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInJvbGUiOiJzdXBlcl9hZG1pbiIsImlhdCI6MTY4Njc1NzAwOCwiZXhwIjoxNjg2ODQzNDA4fQ.4rDRuaMqMbg8ER4xt2w553N1_FcasjM6dj8a1VvSDRI